# Generated by Django 2.2 on 2020-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_comment_confession_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='hashtags',
            field=models.ManyToManyField(null=True, to='mysite.Hashtag'),
        ),
    ]
