# Generated by Django 2.2 on 2020-12-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_commentlike_commentreport_confessionlike_confessionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.Comment'),
        ),
        migrations.AlterField(
            model_name='confessionreport',
            name='confession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.Confession'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='user_comment_constraint'),
        ),
        migrations.AddConstraint(
            model_name='confessionlike',
            constraint=models.UniqueConstraint(fields=('user', 'confession'), name='user_confession_constraint'),
        ),
    ]
